c: -20000
discount_interval: 400
dump_iteration: 10
lcfr_threshold: 400
lut_path: /home/ka/ka_tm/ka_gu4593/pluribus/data/clustering
n_iterations: 1000
n_players: 2
nickname: models/6player
pickle_dir: false
prune_threshold: 400
single_process: false
strategy_interval: 20
sync_cfr: false
sync_discount: false
sync_serialise: false
sync_update_strategy: false
update_threshold: 50
